name: Publish plugin to Gradle Portal

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish package
        run: |
          ./gradlew publishPlugins --info
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PORTAL_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PORTAL_SECRET }}
